-- MySQL 8.x - Chuyển từ SQL Server sang MySQL (InnoDB, utf8mb4)

SET NAMES utf8mb4;
SET time_zone = '+07:00';

DROP DATABASE IF EXISTS `EnglishCenterDB`;
CREATE DATABASE `EnglishCenterDB` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `EnglishCenterDB`;

-- Bảng TAIKHOAN
CREATE TABLE TAIKHOAN (
  MaTaiKhoan INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TenDangNhap VARCHAR(50) NOT NULL UNIQUE,
  MatKhau VARCHAR(255) NOT NULL,
  HoTen VARCHAR(100),
  Email VARCHAR(100),
  SoDienThoai VARCHAR(20),
  VaiTro ENUM('Admin','GiaoVien','HocVien') NOT NULL,
  TrangThai TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB;

-- Bảng GIAOVIEN
CREATE TABLE GIAOVIEN (
  MaGiaoVien INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaTaiKhoan INT UNSIGNED NOT NULL,
  BangCap VARCHAR(100),
  KinhNghiem INT,
  ChuyenMon VARCHAR(100),
  CONSTRAINT fk_gv_taikhoan FOREIGN KEY (MaTaiKhoan) REFERENCES TAIKHOAN(MaTaiKhoan)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

-- Bảng HOCVIEN
CREATE TABLE HOCVIEN (
  MaHocVien INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaTaiKhoan INT UNSIGNED NOT NULL,
  NgayNhapHoc DATE NOT NULL DEFAULT (CURRENT_DATE),
  CONSTRAINT fk_hv_taikhoan FOREIGN KEY (MaTaiKhoan) REFERENCES TAIKHOAN(MaTaiKhoan)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

-- Bảng KHOAHOC
CREATE TABLE KHOAHOC (
  MaKhoaHoc INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TenKhoaHoc VARCHAR(255),
  MoTa LONGTEXT,
  HocPhi DECIMAL(12,2),
  ThoiGianBatDau DATE,
  ThoiGianKetThuc DATE
) ENGINE=InnoDB;

-- Bảng LOPHOC
CREATE TABLE LOPHOC (
  MaLopHoc INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaKhoaHoc INT UNSIGNED,
  MaGiaoVien INT UNSIGNED,
  TenLopHoc VARCHAR(255),
  LichHoc VARCHAR(255),
  PhongHoc VARCHAR(100),
  CONSTRAINT fk_lop_khoahoc FOREIGN KEY (MaKhoaHoc) REFERENCES KHOAHOC(MaKhoaHoc)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_lop_giaovien FOREIGN KEY (MaGiaoVien) REFERENCES GIAOVIEN(MaGiaoVien)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB;

-- Bảng DANGKYHOC
CREATE TABLE DANGKYHOC (
  MaDangKy INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaHocVien INT UNSIGNED,
  MaLopHoc INT UNSIGNED,
  NgayDangKy DATE NOT NULL DEFAULT (CURRENT_DATE),
  TrangThai VARCHAR(50) DEFAULT 'Chưa thanh toán',
  CONSTRAINT fk_dk_hocvien FOREIGN KEY (MaHocVien) REFERENCES HOCVIEN(MaHocVien)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_dk_lophoc FOREIGN KEY (MaLopHoc) REFERENCES LOPHOC(MaLopHoc)
    ON UPDATE CASCADE ON DELETE CASCADE,
  UNIQUE KEY uk_dangky (MaHocVien, MaLopHoc)
) ENGINE=InnoDB;

-- Bảng BAITAP
CREATE TABLE BAITAP (
  MaBaiTap INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaLopHoc INT UNSIGNED,
  MaGiaoVien INT UNSIGNED,
  TieuDe VARCHAR(255),
  NoiDung LONGTEXT,
  HanNop DATETIME,
  CONSTRAINT fk_bt_lophoc FOREIGN KEY (MaLopHoc) REFERENCES LOPHOC(MaLopHoc)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_bt_giaovien FOREIGN KEY (MaGiaoVien) REFERENCES GIAOVIEN(MaGiaoVien)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB;

-- Bảng BAITAP_NOP
CREATE TABLE BAITAP_NOP (
  MaBaiNop INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaBaiTap INT UNSIGNED,
  MaHocVien INT UNSIGNED,
  ThoiGianNop DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  NoiDungTraLoi LONGTEXT,
  FileNop VARCHAR(255),
  Diem DECIMAL(5,2),
  NhanXet VARCHAR(255),
  CONSTRAINT fk_btnop_baitap FOREIGN KEY (MaBaiTap) REFERENCES BAITAP(MaBaiTap)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_btnop_hocvien FOREIGN KEY (MaHocVien) REFERENCES HOCVIEN(MaHocVien)
    ON UPDATE CASCADE ON DELETE CASCADE,
  UNIQUE KEY uk_baitap_nop (MaBaiTap, MaHocVien)
) ENGINE=InnoDB;

-- Bảng DIEM
CREATE TABLE DIEM (
  MaDiem INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaHocVien INT UNSIGNED,
  MaLopHoc INT UNSIGNED,
  DiemGiuaKy DECIMAL(5,2),
  DiemCuoiKy DECIMAL(5,2),
  NhanXet VARCHAR(255),
  CONSTRAINT fk_diem_hocvien FOREIGN KEY (MaHocVien) REFERENCES HOCVIEN(MaHocVien)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_diem_lophoc FOREIGN KEY (MaLopHoc) REFERENCES LOPHOC(MaLopHoc)
    ON UPDATE CASCADE ON DELETE CASCADE,
  UNIQUE KEY uk_diem (MaHocVien, MaLopHoc)
) ENGINE=InnoDB;

-- Bảng PAYMENT
CREATE TABLE PAYMENT (
  MaThanhToan INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MaHocVien INT UNSIGNED,
  SoTien DECIMAL(12,2),
  NgayThanhToan DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PhuongThuc VARCHAR(50),
  TrangThai VARCHAR(50),
  CONSTRAINT fk_payment_hocvien FOREIGN KEY (MaHocVien) REFERENCES HOCVIEN(MaHocVien)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB;
select*from TAIKHOAN

